Refactor + docker-compose-development
steph-koopmanschap/jasma pull request #69
Opened 2023-05-18 04:28 UTC by fflorent-01

###docker-compose-development.yml
- Added x-environment: &dev-environement as a way to share environment varaibles across services
- Added comments to better navigate between services
- TBD reverted to 'postgres', 'redis', 
- Configured jasma-api-server as server
- I revoed -dev from the services names, but kept it for the images names (simplifies the relationship between services as it will stay the same in prod)
- Added a volume so /backend maps to the containe /backend to test changes 'real-time'

###DOCS.md
- Some changes to constant names got carrid over most notable NODE_ENV becomes STAGE

###backend/.env.example
- Should not be needed anymore (TBD)

###backend/docker-entrypoint.sh
- Will run migration at every start

###backend/Dockerfile
- Writen

###backend/pyproject.toml
- Poetry config file (we should figure a unified way to manage dependencies)
- In docker requirements.txt will superseed

###backend/requirements.txt
- Updated, but no way to distinguish --dev dependencies  (pipenv or poetry could allow that)

###backend/api/generate_fake_db.py
- Mostly refactor of class names to make linter quiet and adhere to python naming convention
- Replaced unused variables with _ as per python convention
- Remove unused variables that has no utsefulness

###backend/api/models.py
- Mostly refactor of class names to make linter quiet and adhere to python naming convention
- Replace 'self' where it is supposed to be a self (I know self is a convention but it helps to know that its self)
- Post/Comment now ordered latest first
- A forgottent @ was added to staticmethod

###backend/api/tests.py
- Mostly refactor of class names to make linter quiet and adhere to python naming convention
- Replace 'cls' where it is supposed to be a cls (I know self is a convention but it helps to know that its cls)
- Added a comment at a plae where there is really weird logic (return self.assertTrue(False)) might as well return False

###backend/api/urls.py
- Started reworking the routing schema (nothing was working when using __init__.py

###backend/api/views.py
- Removed as I believe it's interfering with the views folder so they namespace gets confused.

###backend/api/constants/__init__.py
- Added comment on how we could rework constants to be semantically more meaning full
- Notely avoid * import

###backend/api/urls/user_urls.py
- Remove a * import that doesn't seem to be used anyway

###backend/api/utils/handle_file_delete.py / backend/api/utils/handle_file_save.py
- Cleaned up import
- Added custom Error to satisfy linter

###backend/api/views/__init__.py
- Removed * import as this is kindda bad practice

###backend/api/views/auth_views.py
- Currently testting django-rest-framework

###backend/api/views/comment_views.py
- Simplified unecessary embeded if statement
- Removed unused varaible
- Added a question on a suspicious pass statement

###backend/api/views/hashtag_views.py
- Mostly refactor of class names to make linter quiet and adhere to python naming convention
- Comment on a suspicious hashtag argument

###backend/api/views/media_views.py
- Removed * import as this is kindda bad practice

###backend/api/views/notification_views.py
- Mostly refactor of class names to make linter quiet and adhere to python naming convention
- notifTTL renamed NOTIF_TTL as it looked like a constant
- Added a comment about a suspicious variable (and dict) that don't seem to be used in the code

###backend/api/views/post_views.py
- There are a couple of places where I wonder if exceptions migth cause a problem

2023-05-18 11:35 UTC, steph-koopmanschap requested changes

2023-05-18 11:35 UTC, steph-koopmanschap commented on backend/api/views/auth_views.py
def login_view(request): is not allowed to be a GET request.

2023-05-18 11:35 UTC, steph-koopmanschap commented on docker-compose-development.yml
Change NEXT_PUBLIC_STAGE back to NEXT_PUBLIC_NODE_ENV since this is a nodejs environment and not python

2023-05-18 11:35 UTC, steph-koopmanschap commented on next/Dockerfile
Change NEXT_PUBLIC_STAGE back to NEXT_PUBLIC_NODE_ENV since this is a nodejs environment and not python

2023-05-18 11:35 UTC, steph-koopmanschap commented on next/clientAPI/api.js
Change NEXT_PUBLIC_STAGE back to NEXT_PUBLIC_NODE_ENV since this is a nodejs environment and not python

2023-05-18 11:35 UTC, steph-koopmanschap commented on next/next.config.js
Change NEXT_PUBLIC_STAGE back to NEXT_PUBLIC_NODE_ENV since this is a nodejs environment and not python

2023-05-18 11:35 UTC, steph-koopmanschap commented on next/pages/_app.js
Change NEXT_PUBLIC_STAGE back to NEXT_PUBLIC_NODE_ENV since this is a nodejs environment and not python

2023-05-18 17:52 UTC, fflorent-01 commented on backend/api/views/auth_views.py
Fixed

2023-05-18 17:53 UTC, fflorent-01 commented on backend/api/views/hashtag_views.py
> -    req = json.loads(request.body)
I removed req=... as well as it becomes unused

2023-05-18 17:54 UTC, fflorent-01 commented on backend/api/views/comment_views.py
> +        pass  #TODO: Is there something missing here?
This was due to a mistake. It will get fixed.

2023-05-18 17:55 UTC, fflorent-01 commented on backend/api/views/comment_views.py
> -        pass  #TODO: Is there something missing here?
See? I told you it would get fixed :)

2023-05-19 00:33 UTC, steph-koopmanschap approved these changes

2023-05-19 00:34 UTC, merged